# Generated by Django 2.1.2 on 2018-10-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='https://medium.com', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
