# Generated by Django 2.1.2 on 2018-10-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20181025_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topics',
        ),
    ]
