# Generated by Django 2.1.2 on 2018-10-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='article_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
