# Generated by Django 2.1.3 on 2018-11-24 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_link_article_fetched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawler.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='keyword',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
