# Generated by Django 2.1.3 on 2018-11-25 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20181123_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicId', models.IntegerField(blank=True, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('articleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawler.Article')),
            ],
            options={
                'verbose_name': 'ArticleTopic',
                'verbose_name_plural': 'ArticleTopics',
            },
        ),
    ]
