# Generated by Django 2.1.3 on 2018-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20181123_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.IntegerField(),
        ),
    ]
